version: '3.2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_apache
    depends_on:
      - db
    volumes:
      - /Users/aazeroua/Desktop/camagru/camagru/:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysqldb
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
    ports:
      - 6033:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 81:80
    environment:
      PMA_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
volumes:
  db_data: